stump-austin-deters.pdf: stump-austin-deters.tex Makefile
	@rm -f stump-austin-deters.dvi
	@rm -f stump-austin-deters.aux
	latex stump-austin-deters
	bibtex stump-austin-deters
	latex stump-austin-deters
	pdflatex stump-austin-deters


